import { TimelineEvent } from './types';

const now = Date.now();
const mins = (n: number) => new Date(now - n * 60 * 1000).toISOString();
const hrs = (n: number) => new Date(now - n * 60 * 60 * 1000).toISOString();

export const mockEvents: TimelineEvent[] = [
  {
    id: 'evt-001',
    tenantId: 'tenant-demo',
    entityType: 'contact',
    entityId: 'contact-123',
    channel: 'email',
    direction: 'outbound',
    status: 'completed',
    timestamp: mins(30),
    participants: [
      { type: 'from', identifier: 'agent@company.com', name: 'Agent Smith' },
      { type: 'to', identifier: 'john@example.com', name: 'John Doe' },
    ],
    subject: 'Follow-up on your inquiry',
    summary: 'Sent a follow-up email regarding the product demo scheduled for next week.',
    source: 'gmail',
    externalId: 'gmail-001',
    attachments: [],
    metadata: {},
    createdAt: mins(30),
    updatedAt: mins(30),
  },
  {
    id: 'evt-002',
    tenantId: 'tenant-demo',
    entityType: 'contact',
    entityId: 'contact-123',
    channel: 'sms',
    direction: 'inbound',
    status: 'completed',
    timestamp: hrs(2),
    participants: [
      { type: 'from', identifier: '+15551234567', name: 'John Doe' },
      { type: 'to', identifier: '+15559876543', name: 'Support Line' },
    ],
    summary: 'Hi, I wanted to confirm our meeting tomorrow at 2pm.',
    source: 'twilio',
    externalId: 'twilio-002',
    attachments: [],
    metadata: {},
    createdAt: hrs(2),
    updatedAt: hrs(2),
  },
  {
    id: 'evt-003',
    tenantId: 'tenant-demo',
    entityType: 'contact',
    entityId: 'contact-123',
    channel: 'call',
    direction: 'inbound',
    status: 'missed',
    timestamp: hrs(5),
    participants: [
      { type: 'from', identifier: '+15551234567', name: 'John Doe' },
    ],
    summary: 'Missed call from John Doe.',
    source: 'pbx',
    externalId: 'pbx-003',
    attachments: [],
    metadata: {},
    createdAt: hrs(5),
    updatedAt: hrs(5),
  },
  {
    id: 'evt-004',
    tenantId: 'tenant-demo',
    entityType: 'contact',
    entityId: 'contact-123',
    channel: 'note',
    direction: 'internal',
    status: 'completed',
    timestamp: hrs(24),
    participants: [
      { type: 'from', identifier: 'agent@company.com', name: 'Agent Smith' },
    ],
    subject: 'Customer preference noted',
    summary: 'Customer prefers email communication. Do not call before 10am.',
    source: 'crm',
    externalId: 'note-004',
    attachments: [],
    metadata: {},
    createdAt: hrs(24),
    updatedAt: hrs(24),
  },
  {
    id: 'evt-005',
    tenantId: 'tenant-demo',
    entityType: 'contact',
    entityId: 'contact-123',
    channel: 'voip',
    direction: 'outbound',
    status: 'completed',
    timestamp: hrs(48),
    participants: [
      { type: 'from', identifier: 'agent@company.com', name: 'Agent Smith' },
      { type: 'to', identifier: 'john@example.com', name: 'John Doe' },
    ],
    summary: 'Product demo call, 23 minutes. Customer expressed strong interest.',
    source: 'zoom_phone',
    externalId: 'zoom-005',
    detailRef: { type: 'url', value: 'https://zoom.us/rec/share/demo-recording' },
    attachments: [],
    metadata: { durationSeconds: 1380 },
    createdAt: hrs(48),
    updatedAt: hrs(48),
  },
  {
    id: 'evt-006',
    tenantId: 'tenant-demo',
    entityType: 'contact',
    entityId: 'contact-123',
    channel: 'email',
    direction: 'inbound',
    status: 'completed',
    timestamp: hrs(72),
    participants: [
      { type: 'from', identifier: 'john@example.com', name: 'John Doe' },
      { type: 'to', identifier: 'support@company.com', name: 'Support Team' },
    ],
    subject: 'Re: Product inquiry',
    summary: 'Thank you for reaching out. I am interested in the enterprise plan.',
    source: 'gmail',
    externalId: 'gmail-006',
    attachments: [
      { name: 'requirements.pdf', mimeType: 'application/pdf', ref: 'https://drive.google.com/file/d/demo' },
    ],
    metadata: {},
    createdAt: hrs(72),
    updatedAt: hrs(72),
  },
];
